'use strict';

(function () {
  var ESC_KEY = 'Escape';
  var ENTER_KEY = 'Enter';
  var PICTURE_COUNT = 25;
  var DEFAULT_SCALE = 100;
  var MIN_SCALE = 25;
  var MAX_SCALE = 100;
  var STEP_SCALE = 25;
  var MAX_HASHTAGS = 5;
  var MAX_HASHTAG_LENGTH = 20;
  var MAX_HASHTAG_COUNT = 5;
  var MAX_COMMENTS_SYMBOLS = 140;

  window.constants = {
    ESC_KEY: ESC_KEY,
    ENTER_KEY: ENTER_KEY,
    PICTURE_COUNT: PICTURE_COUNT,
    DEFAULT_SCALE: DEFAULT_SCALE,
    MIN_SCALE: MIN_SCALE,
    MAX_SCALE: MAX_SCALE,
    STEP_SCALE: STEP_SCALE,
    MAX_HASHTAGS: MAX_HASHTAGS,
    MAX_HASHTAG_LENGTH: MAX_HASHTAG_LENGTH,
    MAX_HASHTAG_COUNT: MAX_HASHTAG_COUNT,
    MAX_COMMENTS_SYMBOLS: MAX_COMMENTS_SYMBOLS
  };
})();
